// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CockaIO.Models
{
    public partial class Cars
    {
        public Cars()
        {
            UserCar = new HashSet<UserCar>();
        }

        public int Idcar { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string UrlImage { get; set; }

        public virtual ICollection<UserCar> UserCar { get; set; }

    }
}