// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CockaIO.Models
{
    public partial class Users
    {
        public Users()
        {
            UserCar = new HashSet<UserCar>();
        }

        public int Iduser { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public int Age { get; set; }

        public virtual ICollection<UserCar> UserCar { get; set; }
    }
}