// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CockaIO.Models
{
    public partial class UserCar
    {
        public int Iduser { get; set; }
        public int Idcar { get; set; }
        public DateTime? BoughtOn { get; set; }
        public string CarColor { get; set; }
        public string Plate { get; set; }

        public virtual Cars IdcarNavigation { get; set; }
        public virtual Users IduserNavigation { get; set; }
    }
}