// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.IO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using CockaIO.Models;
using System.Linq;
using CockaIO.Services;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Reflection;
#nullable disable

namespace CockaIO.Data
{
    public partial class CockaioContext : DbContext,IDbContextService
    {
        public CockaioContext()
        {
        }

        public CockaioContext(DbContextOptions<CockaioContext> options)
            : base(options)
        {

        }

        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<UserCar> UserCar { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        public bool CreateEntity<T>(T entity) where T : class
        {
            if (this.Add<T>(entity) != null)
            {
                //this.SaveChanges(); Should i put this here?
                return true;
            }
            else return false;
        }

        public bool DeleteEntity<T>(T entity) where T: class
        {
            if (this.Remove<T>(entity) != null)
            {
                //this.SaveChanges(); Should i put this here?
                return true;
            }
            else return false;
        }

        public IQueryable<T> GetAllEntities<T>() where T : class
        {
            return base.Set<T>();
        }

        T GetById<T>(int id) where T : class
        {
            return base.Find<T>(id);
        }

        public bool UpdateEntity<T>(T entity) where T : class
        {
            if (this.Update<T>(entity) != null)
            {
                //this.SaveChanges(); Should i put this here?
                return true;
            }
            else return false;
        }

        public new void SaveChanges() => base.SaveChanges();

        T IDbContextService.GetById<T>(int id)
        {
            return (T)this.Find(typeof(T), id);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                //("8.0.21-mysql")
                //Microsoft.EntityFrameworkCore.Infrastructure.MySqlDbContextOptionsBuilder mySqlDbContextOptionsBuilder = new Microsoft.EntityFrameworkCore.Infrastructure.MySqlDbContextOptionsBuilder(optionsBuilder);
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                string connectionString = File.ReadAllText(@"C:\Users\d4gam\source\repos\CockaIO\CockaIO\Config\ConnectionString.config");
                optionsBuilder.UseMySql(connectionString, new MySqlServerVersion(new Version(8,0,21)));
                
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cars>(entity =>
            {
                entity.HasKey(e => e.Idcar)
                    .HasName("PRIMARY");

                entity.ToTable("cars");

                entity.Property(e => e.Idcar).HasColumnName("idcar");

                entity.Property(e => e.Brand)
                    .IsRequired()
                    .HasColumnType("varchar(45)")
                    .HasColumnName("brand")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Model)
                    .IsRequired()
                    .HasColumnType("varchar(45)")
                    .HasColumnName("model")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.UrlImage)
                    .HasColumnType("varchar(150)")
                    .HasColumnName("url_image")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Year).HasColumnName("year");
            });

            modelBuilder.Entity<UserCar>(entity =>
            {
                entity.HasKey(e => new { e.Iduser, e.Idcar })
                    .HasName("PRIMARY")
                    .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                entity.ToTable("user_car");

                entity.HasIndex(e => e.Idcar, "fk_usercar_car_idx");

                entity.Property(e => e.Iduser).HasColumnName("iduser");

                entity.Property(e => e.Idcar).HasColumnName("idcar");

                entity.Property(e => e.BoughtOn)
                    .HasColumnType("date")
                    .HasColumnName("bought_on");

                entity.Property(e => e.CarColor)
                    .HasColumnType("varchar(45)")
                    .HasColumnName("car_color")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Plate)
                    .HasColumnType("varchar(45)")
                    .HasColumnName("plate")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.IdcarNavigation)
                    .WithMany(p => p.UserCar)
                    .HasForeignKey(d => d.Idcar)
                    .HasConstraintName("fk_usercar_car");

                entity.HasOne(d => d.IduserNavigation)
                    .WithMany(p => p.UserCar)
                    .HasForeignKey(d => d.Iduser)
                    .HasConstraintName("fk_usercar_user");
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.HasKey(e => e.Iduser)
                    .HasName("PRIMARY");

                entity.ToTable("users");

                entity.Property(e => e.Iduser).HasColumnName("iduser");

                entity.Property(e => e.Age).HasColumnName("age");

                entity.Property(e => e.Lastname)
                    .IsRequired()
                    .HasColumnType("varchar(45)")
                    .HasColumnName("lastname")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("varchar(45)")
                    .HasColumnName("name")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);


    }
}